# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_payment_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='transStatus',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
